agent: "MADDPG_EA"
env_name: "NewEnv_MAS"
env_id: "scenarios_0"
max_episode_steps: 2000
render: False
sleep: 0.01
continuous_action: True
policy: "MADDPG_Policy"
representation: "Basic_Identical"
vectorize: "Dummy_NewEnv_MAS"
runner: "MARL_EA"
on_policy: False

actor_hidden_size: [128, 128]
critic_hidden_size: [128, 128]
activation: 'leaky_relu'
activation_action: 'tanh'

seed: 1
parallels: 1
buffer_size: 1000000
batch_size: 1024
lr_a: 0.001  # learning rate for actor
lr_c: 0.001  # learning rate for critic
gamma: 0.99  # discount factor
tau: 0.005  # soft update for target networks

start_noise: 0.1
end_noise: 0.1
sigma: 0.1
start_training: 2000  # start training after n episodes
running_steps: 1000000
train_per_step: True  # True: train model per step; False: train model per episode.
training_frequency: 1

use_grad_clip: True
grad_clip_norm: 0.5

# --- EA options ---
# Only frac (mutation alpha) and state_alpha (beta for VMM) need to be adjusted
EA: 1
rl_to_ea_synch_period: 1
pop_size: 5 # 种群数量
elite_fraction: 0.2 # default setting
mutation_prob: 0.9 # default setting
prob_reset_and_sup: 0.05 # default setting
frac: 1.0 # mutation alpha, see paper for details
pr_dim: 64  # default setting
EA_alpha: 1.0  # default setting
Org_alpha: 1.0 # default setting
N_type: 1 # default setting
SAME: 0  # default setting
start_timesteps: 10000
EA_freq : 1  # default setting
state_alpha: 0.1   # beta control VMM, see paper for details



eval_interval: 10000
test_episode: 1
log_dir: "./logs/maddpg_EA/"
model_dir: "./models/maddpg_EA/"
